
version: "3.5"

services:
  api01: &api
    hostname: api01
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      CLIENT_NAME: "api02"
    env_file:
      - path: ./.env
        required: true # default
    ports:
      - "50051:50051"

  api02:
    hostname: api02
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      CLIENT_NAME: "api01"
    env_file:
      - path: ./.env.other
        required: true # default
    ports:
      - "50052:50052"

networks:
  default:
    driver: bridge
    name: nunet
